### ISSUE TITLE
【インフラ】React環境構築

### ISSUE THREAD

**Issue by tomishima2904** [tomishima2904/shapley_association_game#9]
feature/1/react_env
[こちら](https://qiita.com/shiranon/items/b3efd3ed7ce473c6ad83)の記事をもとにReactの環境をdocker-composeで構築してみる

**Comment by yuma283** [comment]
Reactとは関係ないところでつまづいたので一応共有しておきます。
git push、pullするときにエラーが出たのでその対策として、以下のサイトを参考にした
https://qiita.com/shizuma/items/2b2f873a0034839e47ce
https://trios.pro/github-403-error/#:~:text=%E3%81%A6%E3%81%8D%E3%81%A6%E3%81%BE%E3%81%99%E3%80%82-,Github%E3%81%B8%E3%81%AE%E6%8E%A5%E7%B6%9A%E3%81%8C403%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%AB%E3%81%AA%E3%82%8B%E5%8E%9F%E5%9B%A0,%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E5%87%BA%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82&text=%E3%81%97%E3%81%8B%E3%81%97%E3%80%81%E3%83%91%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89%E3%81%AF%E3%81%82%E3%81%A3%E3%81%A6,%E5%8E%9F%E5%9B%A0%E3%81%8B%E3%82%82%E3%81%97%E3%82%8C%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82%E3%81%93%E3%81%93%E3%82%89%E8%BE%BA%E3%82%92%E4%B8%80%E9%80%9A%E3%82%8A%E8%A9%A6%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B%E3%82%93%E3%81%A0
